name: Continuous Integration Testing

on:
  pull_request:
    branches:
      - 'master'
      - 'main'
  schedule:
    - cron: '0 0 * * *'

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Start Docker-Compose
        run: docker-compose up -d
      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6
          run_install: true
      - name: Run tests
        run: pnpm run test:e2e
      - name: Stop Docker-Compose
        run: docker-compose down
